home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index),
    path('explore', views.index2),
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('story.urls')),
    path('', include('story5.urls')),
    path('', include('story6Baru.urls')),
    path('', include('story7.urls')),
    path('', include('story8.urls')),
    path('', include('story9.urls'))
]

story/urls.py
from django.urls import path

from . import views

app_name = 'story'

urlpatterns = [
    path('index', views.index3, name='index')
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('ListMataKuliah', views.Utama, name='jadwal_list'),
    path('FormMataKuliah',views.formMatkul, name='jadwal_form'),
    path('<int:id>',views.matkulDetail),
    path('deleteMataKuliah/<str:id>', views.deleteMatkul,name="jadwal_delete")
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('homepage', views.homepage, name='homepage'),
    path('story7', views.story7Views, name='story7'),
    # path()
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('search', views.Search, name='search'),
    path('data/', views.SearchInput, name='searchInput'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, 'home/index1.html')

def index2(request):
    return render(request, 'home/explore.html')

home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{% static 'home/shape.png'%}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <title>{% block title %}Welcome!{% endblock %}</title> 
</head>

<body>
<header>  
   <nav class="navbar navbar-expand-lg bg-warning navbar-light fixed-top">
            <a class="navbar-brand" href="/"><img src="{% static 'home/shape.png'%}" class="logo"><b font size="2">&nbsp; Karimah's Website</font></b></a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/#flex">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/explore">Explore</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Story
                    </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="text-align:center;">
                            <a class="dropdown-item" href="{% url 'story:index' %}">Story1</a>
                            <a class="dropdown-item" href="{% url 'story5:jadwal_list' %}">Courses</a>
                            <a class="dropdown-item" href="{% url 'story6Baru:kegiatan_list' %}">Activity</a>
                            <a class="dropdown-item" href="{% url 'story7:homepage' %}">Story7</a>
                            <a class="dropdown-item" href="{% url 'story8:search' %}">Story8</a>
                            <a class="dropdown-item" href="{% url 'story9:login' %}">Story9</a>
                        </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/#contact">Contact</a>
                </li> 
            </ul>
        </div>
    </nav> 
</header>
</body>

{% block content %}

{% endblock %}

<footer id="contact">
    <br><hr width="80%" align="center" height="1px" color="yellow" size="3"><br><br>

    <p style="text-align: center;">
    <b><font size="6">My Contact</font></b><br><br><br>
    </p>

    <p style="text-align: center;">
        <a href="https://www.instagram.com/karimahms"><img src="{% static 'home/myinstagram.svg'%}"></a>
        <a href="mailto:karimahima10@gmail.com"><img src="{% static 'home/email1.svg'%}"></a>
    </p><br>

    <p style="text-align: center;">
    <font size="2" style="color:#4e4e45">Copyright © 2020 Karimah, All Right Reserved</font><br><br>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</footer>