home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index),
    path('explore', views.index2),
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('story.urls')),
    path('', include('story5.urls')),
    path('', include('story6Baru.urls')),
    path('', include('story7.urls')),
    path('', include('story8.urls')),
    path('', include('story9.urls'))
]

story6Baru/urls.py
from django.urls import path

from . import views

app_name = 'story6Baru'

urlpatterns = [
    path('daftar/', views.daftar, name='daftar'),
    path('hapus/', views.hapus, name="hapus"),
    path('ListKegiatan', views.Utama, name='kegiatan_list'),
]

story6Baru/models.py
from django.db import models

# Create your models here.
class KegiatanSaya(models.Model):
    NamaKegiatan = models.CharField(max_length=500)
    Deskripsi = models.TextField (null=True, max_length=500)
    # def __str__(self):
    #     return self.NamaKegiatan
    # def __str__(self):
    #     return self.Deskripsi   

class Participant(models.Model):
    name = models.CharField(max_length = 200)
    kegiatan = models.ForeignKey(KegiatanSaya, on_delete=models.CASCADE)
    # def __str__(self):
    #     return str(self.kegiatan) + " dan " + self.name

story6Baru/forms.py
from django import forms
from .models import KegiatanSaya, Participant

class KegiatanForm(forms.ModelForm):
    NamaKegiatan = forms.CharField()
    Deskripsi = forms.Textarea()
    class Meta:
        model = KegiatanSaya
        fields = '__all__'

class ParticipantForm(forms.ModelForm):
    class Meta:
        model =  Participant
        fields = '__all__'

story6Baru/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import KegiatanSaya, Participant
from .forms import KegiatanForm, ParticipantForm

# Create your views here.
def Utama(request):
    kegiatans = KegiatanSaya.objects.all()
    participants = Participant.objects.all()
    keg_par = []
    for kegiatan in kegiatans:
        kegiatan_partic = []
        for participant in participants:
            if (str(participant.kegiatan) == str(kegiatan)):
                kegiatan_partic.append(participant)
        keg_par.append((kegiatan,kegiatan_partic))
    
    context = {
        "hasil_list" : keg_par
    }
    return render(request, 'story6Baru/kegiatan_list.html', context )

def daftar(request):
    id_kegiatan = request.POST.get('id_kegiatan', None)
    name_participant = request.POST.get('name_participant',None)
    nama_kegiatan = request.POST.get('nama_kegiatan', None)
    deskripsi_kegiatan = request.POST.get('deskripsi_kegiatan', None)

    if (id_kegiatan and name_participant) :
        Participant.objects.create(name=name_participant, kegiatan=KegiatanSaya.objects.get(id = id_kegiatan))
    else:
        KegiatanSaya.objects.create(NamaKegiatan=nama_kegiatan, Deskripsi=deskripsi_kegiatan)

    return redirect('/ListKegiatan')

def hapus(request):
    id_participant = request.POST.get('id_participant', None)
    participant = Participant.objects.get(id = id_participant)
    participant.delete()
    return redirect('/ListKegiatan')
    # return render(request, 'story6Baru/kegiatan_list.html', {'participant' : participant})

story6Baru/templates/story6Baru/kegiatan_list.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block head-footer %}

<header> 
    <br><br><img src="{% static 'story6Baru/form.png'%}" style="height:100%;  overflow:hidden;" class="img-form" alt="Responsive image" loading="lazy">
  </header>
<body>

    <div class="container">
    <p style="text-align: right; margin-top: 20px;">
        <button class="btn btn-primary" data-toggle="modal" data-target="#tambahKegiatan" >Tambah Kegiatan</button>
    </p>

        {% for hasil in hasil_list %}
        
        <div class="card mt-3 " style="margin-bottom: 20px;">
            <div class="card-header bg-info text-white card border-info mb-3">
                <h4>{{hasil.0.NamaKegiatan}}</h2>
            </div>
            <div class="card-body">
                <b>Deskripsi</b>
                <p>{{hasil.0.Deskripsi}}</p>
                <b>Peserta</b>
                {% for participant in hasil.1 %}
                <p class="card-text">{{participant.name}}</p>
                {% endfor %}
                <button class="btn btn-primary" data-toggle="modal" data-target="#tambahParticipant{{ hasil.0.id }}" >Daftar</button>

            </div>
        </div>
    
        
        
        <!-- modal -->  
        <div class="modal fade" id="tambahParticipant{{hasil.0.id}}" tabindex="-1" aria-labelledby="tambahParticipantTitle" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Daftar Ikut Acara {{ hasil.0.NamaKegiatan }} ?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form action="{% url 'story6Baru:daftar' %}" method="post">
                        <div class="modal-body">
                            {% csrf_token %}
                            <input type="hidden" name="id_kegiatan" value="{{hasil.0.id}}">
                            <label for="name_participant">Nama: </label>
                            <input id="name_participant" name="name_participant" type="text" autofocus>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                            <button type="submit" class="btn btn-primary">Daftar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
    </div >
    
    <div class="modal fade" id="tambahKegiatan" tabindex="-1" aria-labelledby="tambahKegiatanTitle" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Daftar Ikut Acara {{ hasil.0.NamaKegiatan }} ?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{% url 'story6:daftar' %}" method="post">
                    <div class="modal-body">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="nama_kegiatan">Nama Kegiatan: </label>
                            <input id="nama_kegiatan" name="nama_kegiatan" type="text" autofocus>
                        </div>
                        <div class="form-group">
                            <label for="deskripsi_kegiatan">Deskripsi Kegiatan: </label>
                            <input id="deskripsi_kegiatan" name="deskripsi_kegiatan" type="text" autofocus>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                        <button type="submit" class="btn btn-primary">Tambah</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body > 
{% endblock %} 