home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index),
    path('explore', views.index2),
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('story.urls')),
    path('', include('story5.urls')),
    path('', include('story6Baru.urls')),
    path('', include('story7.urls')),
    path('', include('story8.urls')),
    path('', include('story9.urls'))
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('ListMataKuliah', views.Utama, name='jadwal_list'),
    path('FormMataKuliah',views.formMatkul, name='jadwal_form'),
    path('<int:id>',views.matkulDetail),
    path('deleteMataKuliah/<str:id>', views.deleteMatkul,name="jadwal_delete")
]

story5/models.py
from django.db import models

# Create your models here.
class MataKuliah(models.Model):
    nama = models.CharField(max_length=50)
    dosen =  models.CharField(max_length=50)
    jumlahSKS = models.PositiveIntegerField()
    deskripsi = models.CharField(max_length=50)
    tahun = models.CharField(max_length=50)
    ruangKelas = models.CharField(max_length=20)

    def __str__(self):
        return self.nama

story5/forms.py
from django import forms

from .models import MataKuliah

class FormMataKuliah(forms.ModelForm):
    nama = forms.CharField()
    dosen =  forms.CharField()
    jumlahSKS = forms.IntegerField()
    deskripsi = forms.CharField()
    tahun = forms.CharField()
    ruangKelas = forms.CharField()

    class Meta:
        model = MataKuliah
        fields = '__all__'

story5/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.http import HttpResponse, Http404
from .models import MataKuliah
from .forms import FormMataKuliah

# Create your views here.
def Utama(request):
    matahkuliahs = MataKuliah.objects.all()
    return render(request, 'story5/jadwal_list.html',{'matakuliahs':matahkuliahs})

def formMatkul(request):
    form = FormMataKuliah()
    if request.method == 'POST':
        form = FormMataKuliah(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/ListMataKuliah')
    return render(request, 'story5/jadwal_form.html',{'form':form})

def matkulDetail(request,id):
    matakuliah = MataKuliah.objects.get(id=id)
    return render(request,'story5/jadwal_details.html',{'matakuliah':matakuliah})

def deleteMatkul(request,id):
    item = MataKuliah.objects.get(id=id)
    if request.method == 'POST' :
        item.delete()
        return redirect('/ListMataKuliah')
    return render(request, 'story5/jadwal_delete.html',{'item':item})

story5/templates/story5/jadwal_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<header>
  <br><br><img src="{% static 'story5/form.png'%}" style="height:100%;  overflow:hidden;" class="img-form" alt="Responsive image" loading="lazy">
</header> 
<div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <h2 class="featurette-heading"><b>Delete course</b></h2>
        <hr class="mt-0 mb-4">
        
        <form action="{% url 'story5:jadwal_delete' item.id %}" method='POST'>
            {% csrf_token %}
            <h5 class="featurette-heading">Do you want to delete the course "{{item}}"?</h5>
            <br>
            <button type="submit" class="btn btn-danger"><b>Yes</b></button>
            <a type="button" class="btn btn-info" href="{% url 'story5:jadwal_list' %}"><b>Cancel</b></a>

      </div>
    </div>
  </div>
<br>

{% endblock %}

story5/templates/story5/jadwal_details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<header>
  <br><br><img src="{% static 'story5/form.png'%}" style="height:100%;  overflow:hidden;" class="img-form" alt="Responsive image" loading="lazy">
</header>
<br><br>
<div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <p><h2 class="featurette-heading"><b>Course Detail</b></h2>
        <table class="table" font size="3" style="text-align: left;" >
        <tbody >
          <tr>
            <th scope="row">Name</th>
            <td>{{ matakuliah.nama }}</td>
          </tr>
          <tr>
            <th scope="row">Lecturer</th>
            <td>{{ matakuliah.dosen }}</td>
          </tr>
          <tr>
            <th scope="row">Credit</th>
            <td>{{ matakuliah.jumlahSKS }}</td>
          </tr>
          <tr>
            <th scope="row">Description</th>
            <td>{{ matakuliah.deskripsi }}</td>
          </tr>
          <tr>
            <th scope="row">Kelas</th>
            <td>{{ matakuliah.ruangKelas }}</td>
          </tr>
          <tr>
            <th scope="row">Semester</th>
            <td>{{ matakuliah.tahun }}</td>
          </tr>
        </tbody>
      </table></p>
      <a class="btn btn-danger" href="{% url 'story5:jadwal_delete' matakuliah.id %}">Delete Course</a>
      <a type="button" class="btn btn-light" href="{% url 'story5:jadwal_list' %}"><b>Back</b></a>
  </div>
</div>
</div>
</br>
{% endblock %}

story5/templates/story5/jadwal_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Form MataKuliah{%endblock%}
{% block content %}

<header>
    <br><br><img src="{% static 'story5/form.png'%}" style="height:100%;  overflow:hidden;" class="img-form" alt="Responsive image" loading="lazy">
</header>
<br><br>
<div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <h2 class="featurette-heading"><b>Add course</b></h2>
        <hr class="mt-0 mb-4">
        <form method='POST'>
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-primary">Submit</button>
            <a type="button" class="btn btn-light" href="{% url 'story5:jadwal_list' %}"><b>Back</b></a>
        </form>
        <br>
      </div>
    </div>
  </div>
<br>
{% endblock %}

story5/templates/story5/jadwal_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<header>
    <br><br><img src="{% static 'story5/form.png'%}" style="height:100%;  overflow:hidden;" class="img-form" alt="Responsive image" loading="lazy">
</header>
<br><br>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <h2 class="featurette-heading"><b>My Courses</b></h2>
        <hr class="mt-0 mb-4">
        <div class="list-group">
            {% for i in matakuliahs %}
            <a href="{{ i.id }}" class="list-group-item list-group-item-action mute-bg"><b>{{ i.nama }}</b></a>
            {% endfor %}
        </div>
        <br>
        <a class="btn btn-warning" href="{% url 'story5:jadwal_form' %}"><b>Add course</b></a>
        <br>
    </div>
    </div>
  </div>
<br>


{% endblock %}